name: Publish to PyPI

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Specify Python 3.11

      # Step 3: Upgrade pip and install required tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      # Step 4: Build the package
      - name: Build package
        run: python -m build

      # Step 5: Publish the package to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
